# Generated by Django 2.2.4 on 2021-08-27 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0003_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='label',
            field=models.ManyToManyField(blank=True, to='dropship.Label'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='watchers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
