# Generated by Django 2.2.4 on 2021-08-31 15:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0005_comment_sprint_worklog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={},
        ),
        migrations.AddField(
            model_name='issue',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dropship.Sprint'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='end',
            field=models.DateField(default=datetime.datetime(2021, 8, 31, 15, 4, 26, 894169, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start',
            field=models.DateField(default=datetime.datetime(2021, 8, 31, 15, 4, 26, 894169, tzinfo=utc)),
        ),
    ]
