# Generated by Django 2.2.4 on 2021-09-06 05:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0006_auto_20210831_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end',
            field=models.DateField(default=datetime.datetime(2021, 9, 6, 5, 51, 13, 238019, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start',
            field=models.DateField(default=datetime.datetime(2021, 9, 6, 5, 51, 13, 238019, tzinfo=utc)),
        ),
    ]
