# Generated by Django 2.2.4 on 2021-09-06 09:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0007_auto_20210906_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end',
            field=models.DateField(default=datetime.datetime(2021, 9, 6, 9, 41, 24, 484911, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start',
            field=models.DateField(default=datetime.datetime(2021, 9, 6, 9, 41, 24, 484911, tzinfo=utc)),
        ),
    ]
