# Generated by Django 3.2.6 on 2021-09-06 09:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0008_auto_20210906_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end',
            field=models.DateField(default=datetime.datetime(2021, 9, 6, 9, 42, 26, 854002, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start',
            field=models.DateField(default=datetime.datetime(2021, 9, 6, 9, 42, 26, 854002, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
