# Generated by Django 2.2.4 on 2021-09-08 06:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0009_auto_20210906_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sprint',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='end',
            field=models.DateField(default=datetime.datetime(2021, 9, 8, 6, 21, 9, 20969, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start',
            field=models.DateField(default=datetime.datetime(2021, 9, 8, 6, 21, 9, 20969, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
